### PR TITLE
Feat/131 user registration full process with interest and institution selection

### PR DESCRIPTION
**Pull request by alereca**

### CODE REVIEW

**Comment by NicoAntonelli** [comment]
Improvement possibility N°1:
The ```Intro``` key's default behaviour is used as "finish" instead of setting current text in place

image


Improvement possibility N°2:
Small alignment issues with "tablet" size

image


Improvement possibility N°3:
When using the searchbar, change URL destination to a useful page like Projects (alt: disable searchbar in this page)

image

**Comment by alereca** [comment]
> Improvement possibility N°1: The `Intro` key's default behaviour is used as "finish" instead of setting current text in place
> 
> image
> 
> Improvement possibility N°2: Small alignment issues with "tablet" size
> 
> image
> 
> Improvement possibility N°3: When using the searchbar, change URL destination to a useful page like Projects (alt: disable searchbar in this page)
> 
> image

`N1` implemented in e7b86b6b9ba38b4bee5dd79ee47a5a7b75be47d6 and 186f43ebcdd11d861253806f2334dbf631388797

**Comment by alereca** [comment]
https://github.com/team120/Universiteams-front/pull/132#issuecomment-2270344720

`N2` implemented in a136fb975aacb36047c807c72f3c75851f9516d0

**Comment by alereca** [comment]
https://github.com/team120/Universiteams-front/pull/132#issuecomment-2270344720

`N3` implemented in 0ecc4c3200dff0ee6faf88c01150d9e998d6cd9b

**Pull request merged**
